language: node_js
node_js:
  - 6
  - 8
  - 10
jobs:
  include:
    - stage: test
      name: "Lint & Test"
      script:
        - npm run eslint
        - npm run test
    - stage: deploy-npm
      name: "npm Deploy"
      before_deploy:
        - npm i --ci
        - npm run postversion
      deploy:
        provider: npm
        skip_cleanup: true
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        on:
          all_branches: true
stages:
  - test
  - name: deploy-npm
    if: branch =~ ^v\d+\.\d+\.\d+-1.*$
