language: node_js
node_js:
  - 0.12
  - 0.1
  - iojs
before_install:
  - npm i -g npm@latest
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
env:
  secure: AF/nHfeDMAbfc6/0WV1dN5T/mMc/UZI+gdFDnNqvG0cLBvc0XtIiX3c4qlq7u77usnNG8EQNkmTwLzpM5wQPfu3HDQRoKehqYyqdKNam0UhhcmuZuMJwFFlOtMYQmDynH0rhGFkDPpnqZboOzrOjASogOfr2Jewtlys+OXcHoeF4431w+BCDJI2BX+nCCDqHoan5DHHzJRsyR2bLOzrfdhm1FllxlnPK0eurb1fwgbiBIieAQHUHN5KCYZ9NcbU+OmdKJUk+xk6tHNDFFgj1vYMwopjXKOzkb33SNpQOcqX67Nuykjo+wbP0XWvJl3Zc8fa/FopdMCyRDWOlVhzNZDHI9B7l+rxq7o7aVRmzpwcLnoDpNyaGEytclWo4MQwtjtqcQ2/D4ob7MoIJaJ/TZJNK4Rnldif4JgLHQhTZ2osc78Qj6s8y8hso2NEuHsW6Wjji6Lt6bFljfe9hfkIMyybE6xRUksY0Crs5TJ5hJl5qNONjMCeLDxsmCz6EOodhKLzZOarTLlbYYhjBRaIrcvxaKQNrEYsedR5MxM799uGVe6sZT1wJPCMif8sHg0KOwe9ikcegvduPa/+yE8WJvMCeBGC8rNd2B3iEFJn2z1rHNTCUMzTrxjv3QjFE2B7Ytwq+dwzkfhF0Y62B+EPKV9WnKTQ+WnXoT/InbZnRLtI=
